report_config = [
    {
        "ReportType": "CricketMatchSummary",
        "Columns": ["Report","League ID","DC Membership","M/F","Date","Day","Division","Season","Away/Guest @ Home/Host","Team","Email","Last Name, FI","Blank","DC","First Name","Legs","L-Win #","L-Win %","","Marks","Darts","MPR","","High Turn","9M","Hat Trick (M)","","Report Link","Event Link"],
        "TableName": "cricket_match_summary"
    },
    {
        "ReportType": "01MatchSummary",
        "Columns": ["Report","League ID","DC Membership","M/F","Date","Day","Division","Season","Away/Guest @ Home/Host","Team","Email","Last Name, FI","Blank","DC","First Name","Legs","L-Win #","L-Win %","","Points","Darts","PPR","","Hi Turn","180s","Hi DO","Hi DI","","Report Link","Event Link"],
        "TableName": "x01_match_summary"
    },
    {
        "ReportType": "CricketMatchCounts",
        "Columns": ["Report","League ID","DC Membership","M/F","Date","Day","Division","Season","Away/Guest @ Home/Host","Team","Email","Last Name, FI","Blank","DC","First Name","Legs","5M+","6M+","Trips (M)","Bulls","Dbulls (M)","","Avg 5M+/Leg","Avg 6M+/Leg","Avg Trips/Leg (M)","Avg Bulls/Leg","Avg DBulls/Leg (M)","","5M+/No TB","6+ Marks/ No TB","Trips/No TB (M)","Bulls/ No TB","DBulls/No TB (M)","","Report Link","Event"],
        "TableName": "cricket_match_counts"
    },
    {
        "ReportType": "01MatchCounts",
        "Columns": ["Report","League ID","DC Membership","M/F","Date","Day","Division","Season","Away/Guest @ Home/Host","Team","Email","Last Name, FI","Blank","DC","First Name","Legs","100+ Points","100+ Count","180's","","100+ Pts/Leg","100+ Ct/Leg","Avg DO","","100+ Pts No TB","100+ cts No TB","Avg DO No TB","180's No TB","","95+ Points","95+ Count","","Report Link","Event Link"],
        "TableName": "x01_match_counts"
    },
    {
        "ReportType": "CricketSeasonSummary",
        "Columns": ["Report","League ID","DC Membership","M/F","Team","Division","Season","Email","Last Name, FI","Blank","DC","First Name","Matches","Legs","L-Win #","L-Win %","","Points","Darts","MPR","","High Turn","9M","Hat Tricks (M)"],
        "TableName": "cricket_season_summary"
    },
    {
        "ReportType": "01SeasonSummary",
        "Columns": ["Report","League ID","DC Membership","M/F","Team","Division","Season","Email","Last Name, FI","Blank","DC","First Name","Matches","Legs","L-Win #","L-Win %","","Points","Darts","PPR","","Hi Turn","180s","Hi DO","Hi DI","Best Leg"],
        "TableName": "x01_season_summary"
    },
    {
        "ReportType": "CricketSeasonCounts",
        "Columns": ["Report","League ID","DC Membership","M/F","Team","Division","Season","Email","Last Name, FI","Blank","DC","First Name","Matches","Legs","5M+","6M+","Trips (M)","Bulls","DBulls (M)","","Avg 5M+/Leg","Avg 6M+/Leg","Avg Trips/Leg (M)","Avg Bulls/Leg","Avg DBulls/Leg (M)","","5M+/No TB","6+ Marks/ No TB","Trips/No TB (M)","Bulls/ No TB","DBulls/No TB (M)"],
        "TableName": "cricket_season_counts"
    },
    {
        "ReportType": "01SeasonCounts",
        "Columns": ["Report","League ID","DC Membership","M/F","Team","Division","Season","Email","Last Name, FI","Blank","DC","First Name","Matches","Legs","100+ Points","100+ Count","180s","","100+ Pts/Leg","100+ Ct/Leg","Avg DO","","100+ Pts No TB","100+ Pts No TB","Avg DO No TB","","180s/Match","180s /Match No TB","","95+ Points","95+ Count"],
        "TableName": "x01_season_counts"
    },
    {
        "ReportType": "MembershipAndEmail",
        "Columns": ["League ID","Division","Match Count","Player Email","Player Name","Team/Division","Host Names","Start Date","Last Date"],
        "TableName": "membership_and_email"
    },
    {
        "ReportType": "HostDeviceInformation",
        "Columns": ["League ID","Division","Host Name","Host Email","Member Level","Player Email","Player Name","Start Date","Last Date"],
        "TableName": "host_device_information"
    },
    {
        "ReportType": "LegExport",
        "Columns": ["Report Name","League ID","Membership","M/F","Team","Division","Season","Email","Last Name, FI","Blank","DC","First Name","PF","Game Name","Win","Start","Cork","","Pts/Marks","Darts","3DA","Hi Turn","DO","DI","","Set #","Game #","","Date","Away @ Guest","Report Link","Event Link"],
        "TableName": "leg_export"
    },

]

column_mapping = {
    "": { "ColumnName": "unknown", "DataType": "VARCHAR(64)" },
    "100+ Count": { "ColumnName": "gte_100_count", "DataType": "INTEGER" },
    "100+ Ct/Leg": { "ColumnName": "gte_100_count_per_leg", "DataType": "DECIMAL(5,2)" },
    "100+ Points": { "ColumnName": "gte_100_points", "DataType": "INTEGER" },
    "100+ Pts No TB": { "ColumnName": "gte_100_points_no_tb", "DataType": "INTEGER" },
    "100+ Pts/Leg": { "ColumnName": "gte_100_pts_per_leg", "DataType": "DECIMAL(5,2)" },
    "100+ cts No TB": { "ColumnName": "gte_100_count_no_tb", "DataType": "INTEGER" },
    "180's No TB": { "ColumnName": "eq_180_count_no_tb", "DataType": "INTEGER" },
    "180's": { "ColumnName": "eq_180_count", "DataType": "INTEGER" },
    "180s /Match No TB": { "ColumnName": "eq_180_pts_per_match_no_tb", "DataType": "DECIMAL(5,2)" },
    "180s": { "ColumnName": "eq_180_count", "DataType": "INTEGER" },
    "180s/Match": { "ColumnName": "eq_180_pts_per_match", "DataType": "DECIMAL(5,2)" },
    "5M+": { "ColumnName": "gte_5m_count", "DataType": "INTEGER" },
    "5M+/No TB": { "ColumnName": "gte_5m_count_no_tb", "DataType": "INTEGER" },
    "6+ Marks/ No TB": { "ColumnName": "gte_6m_count_no_tb", "DataType": "INTEGER" },
    "6M+": { "ColumnName": "gte_6m_count", "DataType": "INTEGER" },
    "95+ Count": { "ColumnName": "gte_95_count", "DataType": "INTEGER" },
    "95+ Points": { "ColumnName": "gte_95_points", "DataType": "INTEGER" },
    "9M": { "ColumnName": "eq_9m_count", "DataType": "INTEGER" },
    "3DA": { "ColumnName": "avg_three_darts", "DataType": "DECIMAL(5,2)" },
    "Avg 5M+/Leg": { "ColumnName": "gte_5m_count_per_leg", "DataType": "DECIMAL(5,2)" },
    "Avg 6M+/Leg": { "ColumnName": "gte_6m_count_per_leg", "DataType": "DECIMAL(5,2)" },
    "Avg Bulls/Leg": { "ColumnName": "bulls_count_per_leg", "DataType": "DECIMAL(5,2)" },
    "Avg DBulls/Leg (M)": { "ColumnName": "dbulls_count_per_leg", "DataType": "DECIMAL(5,2)" },
    "Avg DO No TB": { "ColumnName": "avg_double_out_no_tb", "DataType": "DECIMAL(5,2)" },
    "Avg DO": { "ColumnName": "avg_double_out", "DataType": "DECIMAL(5,2)" },
    "Avg Trips/Leg (M)": { "ColumnName": "avg_triples_per_leg", "DataType": "DECIMAL(5,2)" },
    "Away/Guest @ Home/Host": { "ColumnName": "away_at_home", "DataType": "VARCHAR(64)" },
    "Away @ Guest": { "ColumnName": "away_at_home", "DataType": "VARCHAR(64)" },
    "Best Leg": { "ColumnName": "best_leg", "DataType": "INTEGER" },
    "Blank": { "ColumnName": "blank", "DataType": "VARCHAR(64)" },
    "Bulls": { "ColumnName": "bulls_count", "DataType": "INTEGER" },
    "Bulls/ No TB": { "ColumnName": "bulls_count_no_tb", "DataType": "INTEGER" },
    "Cork": {"ColumnName": "cork", "DataType": "CHAR(1)"},
    "DBulls (M)": { "ColumnName": "dbulls_count", "DataType": "INTEGER" },
    "DBulls/No TB (M)": { "ColumnName": "dbulls_count_no_tb", "DataType": "INTEGER" },
    "DC Membership": { "ColumnName": "dc_membership", "DataType": "VARCHAR(64)" },
    "DC": { "ColumnName": "dc", "DataType": "VARCHAR(64)" },
    "Darts": { "ColumnName": "darts_count", "DataType": "INTEGER" },
    "Date": { "ColumnName": "match_date", "DataType": "DATE" },
    "Day": { "ColumnName": "match_day", "DataType": "VARCHAR(64)" },
    "Dbulls (M)": { "ColumnName": "dbulls_count", "DataType": "INTEGER" },
    "Division": { "ColumnName": "division", "DataType": "VARCHAR(64)" },
    "Email": { "ColumnName": "email", "DataType": "VARCHAR(256)" },
    "Event Link": { "ColumnName": "event_url", "DataType": "VARCHAR(64)" },
    "Event": { "ColumnName": "event", "DataType": "VARCHAR(64)" },
    "First Name": { "ColumnName": "first_name", "DataType": "VARCHAR(64)" },
    "Game Name": { "ColumnName": "game_format", "DataType": "VARCHAR(64)" },
    "Hat Trick (M)": { "ColumnName": "hat_tricks_count", "DataType": "INTEGER" },
    "Hat Tricks (M)": { "ColumnName": "hat_tricks_count", "DataType": "INTEGER" },
    "Hi DI": { "ColumnName": "high_double_in", "DataType": "INTEGER" },
    "Hi DO": { "ColumnName": "high_double_out", "DataType": "INTEGER" },
    "DI": {"ColumnName": "high_double_in", "DataType": "INTEGER"},
    "DO": {"ColumnName": "high_double_out", "DataType": "INTEGER"},
    "Game #": { "ColumnName": "game_number", "DataType": "INTEGER" },
    "Hi Turn": { "ColumnName": "high_turn", "DataType": "INTEGER" },
    "High Turn": { "ColumnName": "high_turn", "DataType": "INTEGER" },
    "Host Email": { "ColumnName": "host_email", "DataType": "VARCHAR(64)" },
    "Host Name": { "ColumnName": "host_name", "DataType": "VARCHAR(64)" },
    "Host Names": { "ColumnName": "host_names", "DataType": "VARCHAR(64)" },
    "L-Win #": { "ColumnName": "leg_wins_count", "DataType": "INTEGER" },
    "L-Win %": { "ColumnName": "leg_wins_pct", "DataType": "DECIMAL(5,2)" },
    "Last Date": { "ColumnName": "last_date", "DataType": "DATE" },
    "Last Name, FI": { "ColumnName": "last_name_fi", "DataType": "VARCHAR(64)" },
    "League ID": { "ColumnName": "league_id", "DataType": "VARCHAR(64)" },
    "Legs": { "ColumnName": "legs_count", "DataType": "INTEGER" },
    "M/F": { "ColumnName": "gender", "DataType": "CHAR(1)" },
    "MPR": { "ColumnName": "mpr", "DataType": "DECIMAL(5,2)" },
    "Marks": { "ColumnName": "marks_count", "DataType": "INTEGER" },
    "Match Count": { "ColumnName": "match_count", "DataType": "INTEGER" },
    "Matches": { "ColumnName": "matches_count", "DataType": "INTEGER" },
    "Member Level": { "ColumnName": "member_level", "DataType": "VARCHAR(64)" },
    "Membership": { "ColumnName": "member_level", "DataType": "VARCHAR(64)" },
    "PF": { "ColumnName": "player_format", "DataType": "CHAR(1)" },
    "PPR": { "ColumnName": "ppr", "DataType": "DECIMAL(5,2)" },
    "Player Email": { "ColumnName": "player_email", "DataType": "VARCHAR(256)" },
    "Player Name": { "ColumnName": "player_name", "DataType": "VARCHAR(256)" },
    "Points": { "ColumnName": "points_total", "DataType": "INTEGER" },
    "Pts/Marks": { "ColumnName": "points_total", "DataType": "INTEGER" },
    "Report Link": { "ColumnName": "report_url", "DataType": "VARCHAR(256)" },
    "Report": { "ColumnName": "report", "DataType": "VARCHAR(128)" },
    "Report Name": { "ColumnName": "report", "DataType": "VARCHAR(128)" },
    "Season": { "ColumnName": "season", "DataType": "VARCHAR(128)" },
    "Set #": { "ColumnName": "set_number", "DataType": "INTEGER" },
    "Start Date": { "ColumnName": "start_date", "DataType": "DATE" },
    "Start": {"ColumnName": "player_format", "DataType": "BOOLEAN"},
    "Team": { "ColumnName": "team_name", "DataType": "VARCHAR(256)" },
    "Team/Division": { "ColumnName": "team_division", "DataType": "VARCHAR(256)" },
    "Trips (M)": { "ColumnName": "triples_count", "DataType": "INTEGER" },
    "Trips/No TB (M)": { "ColumnName": "triples_count_no_tb", "DataType": "INTEGER" },
    "Win": {"ColumnName": "leg_outcome", "DataType": "CHAR(1)"}
}
